app:
  frontend:
    url: http://localhost:3000
cors:
  originPatterns: http://localhost:8080,http://localhost:3000
logging:
  level:
    org.springframework.security: DEBUG
security:
  jwt:
    private:
      key: ${JWT_PRIVATE_KEY}
    public:
      key: ${JWT_PUBLIC_KEY}
server:
  port: ${PORT:8080}
spring:
  application:
    name: trello-clone
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enabled: true
      mail.smtp.starttls.required: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
