cors:
  originPatterns: http://localhost:8080,http://localhost:3000
security:
  jwt:
    private:
      key: ${JWT_PRIVATE_KEY}
    public:
      key: ${JWT_PUBLIC_KEY}
server:
  port: ${PORT:8080}
spring:
  application:
    name: trello-clone
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
